#!/usr/bin/env bash
# Install nginx web server on my server

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/default
ufw allow 'Nginx HTTP'
echo "Holberton School" >> /var/www/html/index.html
service nginx start