#!/usr/bin/env bash
# Configure my Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/default
ufw allow 'Nginx HTTP'
echo "Holberton School" >> /var/www/html/index.html
file_path=/etc/nginx/sites-enabled/default
redirect="\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/$1";
sed -i " /server_name _;/a ${redirect} permanent;" $file_path
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
err="\ error_page\ 404 /custom_404.html;\n\ location\ = \ /custom_404.html\  {\n\t\troot\ /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "/server_name _;/a ${err}" $file_path
service nginx restart
