#!/usr/bin/env bash
# Configure Nginx Server to running, and listening on port 80 of all the server’s active IPv4 IPs

sudo sed -i 's/8080 default_conf/80 default_conf/g' /etc/nginx/conf_d/default_conf
sudo service nginx restart
