#!/usr/bin/env bash
# Configure nginx to stop running
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill "$(cat /var/run/nginx.pid)"
