#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# Requirements:
# 1. Displays FizzBuzz when the number is a multiple of 3 and 5
# 2. Displays Fizz when the number is multiple of 3
# 3. Displays Buzz when the number is a multiple of 5
# 4. Otherwise, displays the number
# 5. In a list format

i=1
while [ $i -le 100 ];
do
    if [ $((i%15)) = 0 ];then
         echo "FizzBuzz"
    elif [ $((i%3)) = 0 ];then
         echo "Fizz"
    elif [ $((i%5)) = 0 ];then
         echo "Buzz"
    else
         echo $i
    fi
    i=$(( i + 1 ))
done
