#!/usr/bin/env bash
# This script displaying "Holberton School" 10 times but diplays "Hi" just after the 9th interation

i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    if [[ $i -eq 9 ]]; then
        echo "Hi"
    fi
    i=$(( i + 1 ))
done
