#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and
# 1.displays bad luck for the 4th loop iteration
# 2.displays good luck for the 8th loop iteration
# 3.displays Holberton School for the other iterations

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi

    i=$(( i + 1 ))
done
