#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts /etc/hosts_copy
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts_copy
sed -i '1s/^/8.8.8.8         facebook.com\n/' /etc/hosts_copy
cp -f /etc/hosts_copy /etc/hosts
