#!/usr/bin/env bash
# A script that copy my  Public SSH Key to a Server with SSH-Copy-ID
# to allow authentication without a password

Host 35.243.201.233
  IdentifyFile ~/.ssh/holberton
  PasswordAuthentication no
  BatchMode yes
